package defines

var CHAIN_CODE_TO_NAME = map[uint8]string{
	CHAIN_CODE_BTC: CHAIN_NAME_BTC,
	CHAIN_CODE_BCH: CHAIN_NAME_BCH,
	CHAIN_CODE_ETH: CHAIN_NAME_ETH,
}

var BUSINESS_CODE_TO_NAME = map[uint8]string{
	BUSINESS_P2P_SWAP:  BUSINESS_P2P_SWAP_NAME,
	BUSINESS_COIN_MINT: BUSINESS_COIN_MINT_NAME,
}

var OFGP_ID = []byte{0x00, 0x66, 0x67, 0x70}

var CONST_OPRETURN = []byte{0x6a, 0x04, 0x00, 0x66, 0x67, 0x70}

var DEFAULT_VERSION = VERSION_01
